### ISSUE TITLE
Upgrade to snakeyaml 1.23

### ISSUE THREAD

**Issue by asarkar** [azagniotov/stubby4j#100]
When using with Spring Boot 2, Stubby4J fails to start because the snakeyaml classes packaged in the jar are not compatible with Spring Boot 2. This has been fixed in Boot 2.1.0.M3, but that doesn't help since Stubby4J is still packaging snakeyaml 1.20. See the following snippet taken from a build scan, which by the way, wasn't possible with the prehistoric version of Gradle that's in the master branch; I'd to locally upgrade to latest Gradle.
![snakeyaml](https://user-images.githubusercontent.com/1302775/45987955-139c4280-c029-11e8-99f7-c88eeb201612.jpg)

This ticket is to upgrade the snakeyaml packaged by Stubby4J to version 1.23.

Reference: https://github.com/spring-projects/spring-boot/issues/13191

**Comment by azagniotov** [comment]
Thanks, will look into this asap

**Comment by asarkar** [comment]
Thank you, please consider upgrading Gradle as well. Like I said above, the build scan made dependency analysis a lot simpler and it isn't available in Gradle 2.0

**Comment by azagniotov** [comment]
I accept PRs :)

**Comment by asarkar** [comment]
> I accept PRs :)

I'm sure you do, but do you really need help for changing some text from `2.0` to `4.10.2`?

**Comment by moleksyuk** [comment]
> I accept PRs :)

@azagniotov see my pull request #105

**Comment by moleksyuk** [comment]
@azagniotov 
**Tested with**: `v6.0.2`
**Status**: ✅ Fixed
This ticket can be closed.
