### ISSUE TITLE
[FEATURE REQUEST] Create a client to simplify configuration through HTTP 

### ISSUE THREAD

**Issue by LenarBad** [azagniotov/stubby4j#238]
We could give users the tool (Java client) to configure a running Stubby4j instance programmatically from the code without having to implement the stubby4j admin client.

Example of the admin client implementation for reference - [Admin Client](https://www.lenar.io/dependency-and-error-testing-with-stubby4j/)

**Comment by azagniotov** [comment]
@LenarBad in the meanwhile before I get to this, and somewhat on the topic, I updated the documentation about the management REST API, could you have a look? I appreciate your feedback: https://github.com/azagniotov/stubby4j/blob/master/ADMIN_PORTAL.md

**Comment by azagniotov** [comment]
@LenarBad Perhaps the following can help you when configuring stubs through HTTP via the admin portal. stubby4j has a class `YamlBuilder`, a builder, that enabled you to build a YAML string, which can be used as a payload. I admit that this is not obvious from the docs. You can then make a `PUT` request to the admin portal. 

I [wrote a test to demonstrate the usage](https://github.com/azagniotov/stubby4j/blob/master/src/functional-test/java/io/github/azagniotov/stubby4j/ProxyConfigWithStubsTest.java#L203) of the  [YamlBuilder](https://github.com/azagniotov/stubby4j/blob/master/src/main/java/io/github/azagniotov/stubby4j/yaml/YamlBuilder.java) and [StubbyClient#updateStubbedData(...)](https://github.com/azagniotov/stubby4j/blob/master/src/main/java/io/github/azagniotov/stubby4j/client/StubbyClient.java#L433) when updating `proxy-config`  configuration by `uuid`.

Although my test is about `proxy-config`, you can also use the same builder to create/update stub `request` with its `response`. 

See if this can work for you or any refinement is needed

**Comment by azagniotov** [comment]
@LenarBad I hope all is good on your end. I will close this in the meanwhile, feel free to reopen.
