### ISSUE TITLE
string comaprision of post request

### ISSUE THREAD

**Issue by paramadeep** [azagniotov/stubby4j#32]
I'm facing a issue with handling response for a post request. We use stubby4j for our UI automation. We stub all the service calls. The tests fails randomly for when it comes to post calls.
The problem with the post request is, the json that comes with the request though it have same key value pair, their order is different each time. 
I understand we as using string comparison for post files, instead if we could do key value pair comparison it would be great.

**Comment by azagniotov** [comment]
Will look into it

**Comment by azagniotov** [comment]
In the next version (3.0.4), in case of POSTed data type is `application/json`, the comparison to stubbed POST data will be done using JSON entities with non-strict checking (content ordering wont matter, as long as it is the same)

**Comment by azagniotov** [comment]
sorry, the latest version is: 3.1.3 https://github.com/azagniotov/stubby4j#313
