### ISSUE TITLE
Error Count details

### ISSUE THREAD

**Issue by paramadeep** [azagniotov/stubby4j#33]
This is more of a feature request. 
Currently in our application, there are places where we just make a request and we'll not act on the response. In such places we are not able to assert if such call we made. This makes our tests incomplete.
Currently we are parsing the stub log to see if it has any error, to ensure all the request made to are valid. This is not very clean, instead if we have a end point to give number of error raised, we would use that to assert if all the request are valid.

**Comment by azagniotov** [comment]
Sorry. I was away from this for a very long time. I like this idea. Once stubby is upgraded to v9, I will look into this
