### ISSUE TITLE
Start Jetty Server without YAML configuration file

### ISSUE THREAD

**Issue by deepakl** [azagniotov/stubby4j#35]
For our integration tests, we setup stub responses (using the POST endpoint) before each scenario and then refresh the stubs afterwards.
However, I still need to create a dummy YAML configuration file to boot up the Jetty server.

It would be nice if the YAML file is optional parameter to `startJetty` to avoid creating a dummy file.

**Comment by azagniotov** [comment]
One year later. It would be possible to start stubby programmatically without creating a dummy file in the next version (v3.0.1)
