### ISSUE TITLE
Stubby4j matching on request body does not work whenever "?" is part of request body.

### ISSUE THREAD

**Issue by itzmanjeet** [azagniotov/stubby4j#37]
We configured a request on Stubby4j. There is ? in the top header. Whenever I remove question marks from the line <?xml version='1.0' encoding='UTF-8'?> then request and response work correctly, whenever there is any question mark in this line 404 comes up as ? mark is hampering that request matching. Can anybody suggest how to fix this or any work around this. ? mark is mandatory part of request.

**Comment by mrak** [comment]
I believe this is because stubby interprets configured values as regular expressions. Is there something in particular within the body you want to match on instead of the entire body?

**Comment by itzmanjeet** [comment]
Yes, we need to match few unique identifiers in some elements of the request body xml. These identifiers can across multiple line in request body as elements can increase or decrease based on the request. 

Like in below sample xml we want to match few element values like senderId, ID , passcode. Say if the senderId=adcdc, ID= 123455667 and passcode=passcode1, then only response should be returned.

<?xml version='1.0' encoding='UTF-8'?>
<ns1:Envelope xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/">
	<ns1:Body       
		<sender>           
			<senderId>adcdc</senderId>           
			<channelId>test</channelId>           
			<applicationId>xyz</applicationId>           
			<applicationUserId>manjeet</applicationUserId>           
			<workflowId>00000</workflowId>           
			<activityId>activity1</activityId>           
			<storeId>store1</storeId>           
			<dealerCode>22222</dealerCode>         
		</sender>       
		</header>       
		<ID>123455667</ID>       
		<passcode>passcode1</passcode>     
	</ns1:Body>
</ns1:Envelople>

**Comment by itzmanjeet** [comment]
Hi Mrak,

Can please suggest some thing which can help to get around this problem.

Thanks,
Manjeet

**Comment by itzmanjeet** [comment]
Can anyone please provide any help on our issue?

Thanks,
Manjeet

**Comment by mrak** [comment]
Can you post your YAML of the endpoint you're trying to match?

XML was some characters (like '?') that are meaningful in regular expressions. You will have to escape these characters for them to be interpreted literally.

**Comment by itzmanjeet** [comment]
Thanks Eric for this, using escape character before ? worked.

We need your help regarding regex pattern as well. In our case the request body posted on the stubby4j side span across multiple lines. We need a regex pattern to match few unique identifiers in mutli line request body. We formed a pattern that can match the identifier across multiple lines, however whenever the identifier is not present there in the request body, this regex pattern goes into kind of infinite loop and doesn't comes back. Our regex pattern is failing for negative scenario i.e. no match. Is there a regex pattern in which both the cases work for match and no match ?

**Comment by itzmanjeet** [comment]
Please let us know if you anybody can help us on this ?

**Comment by mrak** [comment]
I can't imagine a regular expression going into an infinite loop.

Could you post the exact endpoint you have configured in your YAML and the types of requests you are making?

It sounds like a matter of how to represent your regular expression

**Comment by azagniotov** [comment]
Closing due to no response
