### ISSUE TITLE
Logging in Stubby4j

### ISSUE THREAD

**Issue by itzmanjeet** [azagniotov/stubby4j#38]
Is there a way we can increase the log level in Stubby4j? As of now we see very little information in stubby4j logs, can we some how increase the logging level in Stubby4j. Our intend is to see in the logs the request body which is getting posted on Stubby4j URL and any exception that is occurring in stubby4j.

**Comment by mrak** [comment]
At one point we had a `--debug` flag (which was very verbose), but that feature may not have stuck around.

@azagniotov is there still a programmatic way to trigger verbose logging of stubby?

**Comment by azagniotov** [comment]
Nope... There is no more verbose logging available.

**Comment by azagniotov** [comment]
Will add verbose logging in a few days

**Comment by azagniotov** [comment]
Added `--debug` options that dumps raw HTTP request to console

**Comment by vickylalit** [comment]
Hi,
I am using stubby4j for REST APIs testing. From what I understand, it dump the Request and Responses in Console via ANSITerminal.

Is there a way to override these. I want to send these logs to SocketAppender/FileAppender.

Any feedback is much appreciated.
