### ISSUE TITLE
Can we start stubby using startJetty() with ssl and admin portal disabled?

### ISSUE THREAD

**Issue by nitinpadalia** [azagniotov/stubby4j#40]
It'll be great if stubby has this feature of disabling SSL and admin portal, so that it could run inside application in cloud environment too.

-Nitin

**Comment by azagniotov** [comment]
Hi! I will add this feature in a few days

**Comment by azagniotov** [comment]
Also, can you please provide more information about how SSL and admin portal preventing you from running the stubby in cloud environment?

**Comment by nitinpadalia** [comment]
Thanks! a lot Alexander for looking into it.
Actually we're trying to run stubby inside CloudFoundry, but since Stubby Jetty require these ports necessarily. Inside CloudFoudry we don't have much flexibility regarding ports as if we bind to our custom ports CF router won't be able to route these ports natively as well as this won't be a very scalable test service as ports are bound to hard coded one.

For Jetty port we're working around running Jetty on dynamic port provided by CloudFoundry. It would be great if that port requirement could also be removed, i.e.; Stubby could run directly inside our Webapp.

**Comment by azagniotov** [comment]
I see. I can make two options:
`--disable_admin_portal` and `--disable_ssl_portal` which respectively would disable admin portal & SSL. Would this work?

**Comment by azagniotov** [comment]
Added the two options above in v3.0.1
