### ISSUE TITLE
Multiple POST request for same URL

### ISSUE THREAD

**Issue by am78** [azagniotov/stubby4j#41]
I want to configure multiple POST request for the same URL but with different body data.
But only the first configured request is working properly.
When the second configured request matches, stubby4j seems to hang up and no response is send back to client.
Is this a known problem? Is there some kind of workaround available?
Thanks,
Michael

**Comment by azagniotov** [comment]
Can I have a look at your YAML? At the stage you can configure multiple stubbed responses on the same stubbed URL. That being said, you can configure your POST to be a regex (I do not know how complex your POST data is): 
```
-  request:
      method: [POST]
      url: /uri/with/post/regex
      post: "^[\\.,'a-zA-Z\\s+]*$"
```
Also, do you expected different response per each POST?

**Comment by am78** [comment]
Thanks for your quick response.
I just tried the same approach with simplified data and it worked well.
So maybe there is an error on my side in my regex or so.

Currently I’m not at the office and cannot use the exact configuration, I will try it again next week. Hope I get it to work then.
In my case I have one Endpoint but different SOAP requests and depending on the request different SOAP responses.

bye,
Michael

**Comment by am78** [comment]
Got it to work with adjusted RegExp in request post value.
Thanks for your help.

**Comment by azagniotov** [comment]
Cheers

**Comment by tiago-rocha-gomes** [comment]
> Can I have a look at your YAML? At the stage you can configure multiple stubbed responses on the same stubbed URL. That being said, you can configure your POST to be a regex (I do not know how complex your POST data is):
> 
> ```
> -  request:
>       method: [POST]
>       url: /uri/with/post/regex
>       post: "^[\\.,'a-zA-Z\\s+]*$"
> ```
> Also, do you expected different response per each POST?

Hi guys, sorry for reopen this thread. I would to do exactly this. How can I do? 
Thanks!
My YAML:

`-  request:
      url: /privado/Alelo/Beneficios/CompanyService
      method: POST
      post: >
         <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:com="http://CompanyService.integrador.alelo.com.br">
            <soap:Header/>
            <soap:Body>
               <com:ListSpokesmanISRequest>
                  <spokesmanCPF>89861778039</spokesmanCPF>
                  <contracteeDocumentType>CNPJ</contracteeDocumentType>
                  <contracteeDocumentNumber>41494475000169</contracteeDocumentNumber>
                  <pagingData>
                     <indexPage>1</indexPage>
                     
                     <size>100</size>
                  </pagingData>
                  <communicationData>
                     <product>1</product>
                     <institution>ALELO</institution>
                     <channel>WEB</channel>
                     <usn>1234</usn>
                  </communicationData>
               </com:ListSpokesmanISRequest>
            </soap:Body>
         </soap:Envelope>
   response:
    - status: 200
      latency: 5000
      headers:
         Content-Type: application/xml
      body: >
         <soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
            <soapenv:Body>
               <NS1:ListSpokesmanISResponse xmlns:NS1="http://CompanyService.integrador.alelo.com.br">
                 <responseData>
                    <success>true</success>
                    <clrs>ALELO,4,WEB,1234,1,2019-01-30 15:39:23.093803</clrs>
                    <communicationData>
                       <product>1</product>
                       <institution>ALELO</institution>
                       <channel>WEB</channel>
                       <usn>1234</usn>
                    </communicationData>
                 </responseData>
                 <recordsCount>1</recordsCount>
                 <shortListCompany>
                    <companyDocumentType>CNPJ</companyDocumentType>
                    <companyDocumentNumber>41494475</companyDocumentNumber>
                    <legalName>Empresa que nasceu PME</legalName>
                    <spokesmanList>
                       <listSpokesmanData>
                          <shortListContractee>
                             <shortListContractee>
                                <contracteeDocumentType>CNPJ</contracteeDocumentType>
                                <contracteeDocumentNumber>41494475000169</contracteeDocumentNumber>
                                <contracteeLegalName>PAULISTÃO SUPERMERCADOS</contracteeLegalName>
                                <branchSpokesman>
                                   <branchSpokesman>
                                      <functionType>OPERATION</functionType>
                                      <contractNumberList>
                                         <contractNumber>11345317</contractNumber>
                                      </contractNumberList>
                                   </branchSpokesman>
                                </branchSpokesman>
                             </shortListContractee>
                          </shortListContractee>
                          <spokesman>
                             <companyDocumentNumber>41494475</companyDocumentNumber>
                             <companyDocumentType>CNPJ</companyDocumentType>
                             <spokesmanName>COLABORADOR NOVO</spokesmanName>
                             <birthDate>1990-01-01</birthDate>
                             <documentNumber>85348631213</documentNumber>
                             <gender>MALE</gender>
                             <jobType>MANAGER</jobType>
                             <commercialAdressType>BRANCH</commercialAdressType>
                             <commercialAddress>
                                <addressType/>
                                <street/>
                                <postalCode/>
                                <countryISOCode/>
                                <stateISOCode/>
                                <cityName/>
                             </commercialAddress>
                             <localization>COLABORADOR NOVO DEP</localization>
                             <email>alelo-canais-hydra@ciandt.com</email>
                             <phone1>
                                <phoneType>PHONE</phoneType>
                                <countryCode>55</countryCode>
                                <areaCode>19</areaCode>
                                <phoneNumber>999999999</phoneNumber>
                             </phone1>
                             <phone2>
                                <phoneType/>
                                <countryCode/>
                                <areaCode/>
                                <phoneNumber/>
                             </phone2>
                             <fax>
                                <phoneType/>
                                <countryCode/>
                                <areaCode/>
                                <phoneNumber/>
                             </fax>
                          </spokesman>
                       </listSpokesmanData>
                       <listSpokesmanData>
                          <shortListContractee>
                             <shortListContractee>
                                <contracteeDocumentType>CNPJ</contracteeDocumentType>
                                <contracteeDocumentNumber>41494475000169</contracteeDocumentNumber>
                                <contracteeLegalName>PAULISTÃO SUPERMERCADOS</contracteeLegalName>
                                <branchSpokesman>
                                   <branchSpokesman>
                                      <functionType>OPERATION</functionType>
                                      <contractNumberList>
                                         <contractNumber>11345317</contractNumber>
                                      </contractNumberList>
                                   </branchSpokesman>
                                   <branchSpokesman>
                                      <functionType>RECEPTION</functionType>
                                      <branchList>
                                         <shortListBranch>
                                            <branchSubtype>BRANCH</branchSubtype>
                                            <branchName>Filial Dois</branchName>
                                            <branchDocumentType>CNPJ</branchDocumentType>
                                            <branchDocumentNumber>41494475000320</branchDocumentNumber>
                                            <relevanceOrder>1</relevanceOrder>
                                         </shortListBranch>
                                         <shortListBranch>
                                            <branchSubtype>BRANCH</branchSubtype>
                                            <branchName>PAULISTÃO SUPERMERCADOS</branchName>
                                            <branchDocumentType>CNPJ</branchDocumentType>
                                            <branchDocumentNumber>41494475000169</branchDocumentNumber>
                                            <relevanceOrder>1</relevanceOrder>
                                         </shortListBranch>
                                         <shortListBranch>
                                            <branchSubtype>BRANCH</branchSubtype>
                                            <branchName>SÃO PAULO</branchName>
                                            <branchDocumentType>CNPJ</branchDocumentType>
                                            <branchDocumentNumber>41494475000401</branchDocumentNumber>
                                            <relevanceOrder>1</relevanceOrder>
                                         </shortListBranch>
                                         <shortListBranch>
                                            <branchSubtype>BRANCH</branchSubtype>
                                            <branchName>TAQUARAL</branchName>
                                            <branchDocumentType>CNPJ</branchDocumentType>
                                            <branchDocumentNumber>41494475000240</branchDocumentNumber>
                                            <relevanceOrder>1</relevanceOrder>
                                         </shortListBranch>
                                      </branchList>
                                   </branchSpokesman>
                                   <branchSpokesman>
                                      <functionType>BILLING</functionType>
                                      <branchList>
                                         <shortListBranch>
                                            <branchSubtype>BRANCH</branchSubtype>
                                            <branchName>Filial Dois</branchName>
                                            <branchDocumentType>CNPJ</branchDocumentType>
                                            <branchDocumentNumber>41494475000320</branchDocumentNumber>
                                            <relevanceOrder>1</relevanceOrder>
                                         </shortListBranch>
                                         <shortListBranch>
                                            <branchSubtype>BRANCH</branchSubtype>
                                            <branchName>PAULISTÃO SUPERMERCADOS</branchName>
                                            <branchDocumentType>CNPJ</branchDocumentType>
                                            <branchDocumentNumber>41494475000169</branchDocumentNumber>
                                            <relevanceOrder>1</relevanceOrder>
                                         </shortListBranch>
                                         <shortListBranch>
                                            <branchSubtype>BRANCH</branchSubtype>
                                            <branchName>SÃO PAULO</branchName>
                                            <branchDocumentType>CNPJ</branchDocumentType>
                                            <branchDocumentNumber>41494475000401</branchDocumentNumber>
                                            <relevanceOrder>1</relevanceOrder>
                                         </shortListBranch>
                                         <shortListBranch>
                                            <branchSubtype>BRANCH</branchSubtype>
                                            <branchName>TAQUARAL</branchName>
                                            <branchDocumentType>CNPJ</branchDocumentType>
                                            <branchDocumentNumber>41494475000240</branchDocumentNumber>
                                            <relevanceOrder>1</relevanceOrder>
                                         </shortListBranch>
                                      </branchList>
                                   </branchSpokesman>
                                   <branchSpokesman>
                                      <functionType>DECISION</functionType>
                                      <contractNumberList>
                                         <contractNumber>11345317</contractNumber>
                                      </contractNumberList>
                                   </branchSpokesman>
                                   <branchSpokesman>
                                      <functionType>FINANCIAL</functionType>
                                   </branchSpokesman>
                                </branchSpokesman>
                             </shortListContractee>
                          </shortListContractee>
                          <spokesman>
                             <companyDocumentNumber>41494475</companyDocumentNumber>
                             <companyDocumentType>CNPJ</companyDocumentType>
                             <spokesmanName>Nono Miquelle</spokesmanName>
                             <birthDate>1990-01-01</birthDate>
                             <documentNumber>89861778039</documentNumber>
                             <gender>MALE</gender>
                             <jobType>DIRECTOR</jobType>
                             <commercialAdressType>BRANCH</commercialAdressType>
                             <commercialAddress>
                                <addressType/>
                                <street/>
                                <postalCode/>
                                <countryISOCode/>
                                <stateISOCode/>
                                <cityName/>
                             </commercialAddress>
                             <localization>DEPTO PESSOAL</localization>
                             <idUser>22257</idUser>
                             <email>alelo-canais-hydra@ciandt.com</email>
                             <phone1>
                                <phoneType>PHONE</phoneType>
                                <countryCode>55</countryCode>
                                <areaCode>11</areaCode>
                                <phoneNumber>21886152</phoneNumber>
                             </phone1>
                             <phone2>
                                <phoneType/>
                                <countryCode/>
                                <areaCode/>
                                <phoneNumber/>
                             </phone2>
                             <fax>
                                <phoneType/>
                                <countryCode/>
                                <areaCode/>
                                <phoneNumber/>
                             </fax>
                          </spokesman>
                       </listSpokesmanData>
                    </spokesmanList>
                 </shortListCompany>
              </NS1:ListSpokesmanISResponse>
            </soapenv:Body>
         </soapenv:Envelope>

-  request:
      url: /privado/Alelo/Beneficios/CompanyService
      method: POST
      post: >
         <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:com="http://CompanyService.integrador.alelo.com.br">
            <soap:Header/>
            <soap:Body>
               <com:ListSpokesmanISRequest>
                  <spokesmanCPF>89861778039</spokesmanCPF>
                  <contracteeDocumentType>CNPJ</contracteeDocumentType>
                  <contracteeDocumentNumber>41494475000168</contracteeDocumentNumber>
                  <pagingData>
                     <indexPage>1</indexPage>
                     
                     <size>100</size>
                  </pagingData>
                  <communicationData>
                     <product>1</product>
                     <institution>ALELO</institution>
                     <channel>WEB</channel>
                     <usn>1234</usn>
                  </communicationData>
               </com:ListSpokesmanISRequest>
            </soap:Body>
         </soap:Envelope>
   response:
    - status: 200
      latency: 5000
      headers:
         Content-Type: application/xml
      body: >
         <soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
           <soapenv:Body>
              <NS1:ListSpokesmanISResponse xmlns:NS1="http://CompanyService.integrador.alelo.com.br">
                <responseData>
                    <success>false</success>
                    <errorList>
                       <errorData>
                          <errorCode>CT0278</errorCode>
                          <errorMessage>CPF ou CNPJ não cadastrado.</errorMessage>
                       </errorData>
                      <errorDataListSize>1</errorDataListSize>
                   </errorList>
                   <clrs>ALELO,4,WEB,1234,1,2019-01-30 15:52:33.143831</clrs>
                   <communicationData>
                      <product>1</product>
                      <institution>ALELO</institution>
                      <channel>WEB</channel>
                      <usn>1234</usn>
                   </communicationData>
                </responseData>
                <recordsCount>0</recordsCount>
              </NS1:ListSpokesmanISResponse>
           </soapenv:Body>
         </soapenv:Envelope>`
