### ISSUE TITLE
Live refresh in response sequence only for first response

### ISSUE THREAD

**Issue by TobiasHeinicke** [azagniotov/stubby4j#43]
The live refresh of external files in a sequence of responses only works for the file in first entry.
Take this as an example:

    response:
        -   status: 200
            headers:
                content-type: application/xml
            file: ../responses/first.xml

        -   status: 200
            headers:
                content-type: application/xml
            file: ../responses/second.xml

If "first.xml" is subject to changes the live refresh is performed, if however "second.xml" changes no live refresh is done. If second.xml is included in another response (as first or only entry) then it will change, too.

**Comment by azagniotov** [comment]
Ah thanks :+1:  I will have a look :)

**Comment by azagniotov** [comment]
Fixed in v3.0.3
