### ISSUE TITLE
Request and response bodies not coming

### ISSUE THREAD

**Issue by ravesean** [azagniotov/stubby4j#45]
I've used ConsoleUtils.enableDebug(true) to get request and response bodies on console, but not able to get .
Kindly look into it, in our use case requirement in which when any request gets failed at stubby's end then we want to see request and response body for debugging , but currently it is not dumping the same.

**Comment by azagniotov** [comment]
Please use `--debug` command line argument if you are running stubby using the `java -jar ...` command
