### ISSUE TITLE
for websocket on-message's  client request from the text file new line (Enter) not accepted by using of stubby4j any solution or guideline to use new line in requested file, my requirement is, in requested text file must use multiline value

### ISSUE THREAD

**Issue by kumarpramodlohar** [azagniotov/stubby4j#457]
**Please provide some basic information about you environment**
- What is your OS: Windows/Mac/*Nix:
- What is stubby4j version you are running:
- Are you running stubby4j in Docker container or as a standalone JAR: 
- If Docker container, what is the image tag:

**Is your question request related to a problem? Please describe.**

**Provide details about your question**

**Additional context**
Add any other context or screenshots about the question here.

**Comment by azagniotov** [comment]
Hi @kumarpramodlohar , it is hard to understand 100% what your problem is since you packed so much information into the issue subject field. Can you please describe in detail using a new comment what is your use-case and what you are trying to achieve.  Thank you

**Comment by kumarpramodlohar** [comment]
Hi azagniotov,
I have one microservice for getting real time information, using spring boot, websocket, stomp, kafka for messages broker, scenario is I need to stubbed this service for the developer, they use this mocking service in his local, so I am facing below issues when I used this library.

**Comment by azagniotov** [comment]
@kumarpramodlohar thank you. Would you be able to provide an example of the YAML config you used for stubby4j? I will need it in order to try to reproduce the behavior you are seeing

**Comment by kumarpramodlohar** [comment]
[yml&request.zip](https://github.com/azagniotov/stubby4j/files/9786313/yml.request.zip)

Hi azagniotov,
Thanks for your prompt reply, please find zip file for yml config and also sample of request file attached.

**Comment by kumarpramodlohar** [comment]
Hi Azagniotov,
Any suggestion or solutions, please let me know, I am waiting for your response.

**Comment by azagniotov** [comment]
Hi Kumar,

I have not had a chance to deep dive into this just yet.

I appreciate your patience
