### ISSUE TITLE
[FEATURE REQUEST] ... Support ARM Docker Images

### ISSUE THREAD

**Issue by dnatic09** [azagniotov/stubby4j#458]
**Is your feature request related to a problem? Please describe.**
Docker images cannot run on ARM/M1 architecture

**Describe the solution you'd like**
Docker images to be published from CircleCI to Docker Hub with ARM support

**Describe alternatives you've considered**
I have tried emulation, but it is not nearly as good

**Additional context**

If `circleci` is running with `buildx`, you just need to change this line:
https://github.com/azagniotov/stubby4j/blob/master/.circleci/config.yml#L269

from:
```
 command: docker build --rm --no-cache -t azagniotov/stubby4j:latest-jre<< parameters.jdk_version >> .
```

to:
```
command: docker build --platform linux/amd64,linux/arm64,--rm --no-cache -t azagniotov/stubby4j:latest-jre<< parameters.jdk_version >> .
```

**Comment by azagniotov** [comment]
Daniel, I will push ARM images the coming weekOn Jan 13, 2024, at 5:20, Daniel Natic ***@***.***> wrote:﻿
Closed #458 as not planned.

**Comment by dnatic09** [comment]
Thank you. We appreciate you circling back and closing this gap. It was difficult for Apple Silicon engineers to use this software previously without emulators or hacks.

**Comment by azagniotov** [comment]
No problem.  I myself recently has moved to Apple Silicon. It will take me a few tries, please allow me sometime

**Comment by azagniotov** [comment]
I achieved some progress with publishing multiple arch images, see the latest-jre11: https://hub.docker.com/layers/azagniotov/stubby4j/latest-jre11/images/sha256-22a50332f75497b65a876ed245aefedda736c4e0b09dff81d389cc661240f0ca?context=explore 

But, please do not use. I need to clean up the PR first: https://github.com/azagniotov/stubby4j/pull/465

**Comment by dnatic09** [comment]
Not sure if it was on purpose or not. You broke the JDK16 image by using a JDK17 base image.

**Comment by azagniotov** [comment]
@dnatic09 apologies for the mix up. The JDK 16 latest image on Docker Hub has been reverted to its previous state

**Comment by dnatic09** [comment]
No worries. Does not hurt my feelings either way. Just did not want other consumers to be confused.

**Comment by azagniotov** [comment]
Thank you for bringing this to my attention 👍🏼

**Comment by dnatic09** [comment]
I see a JRE8 and JRE11 image on Docker Hub. Will JRE17 follow soon?

**Comment by azagniotov** [comment]
@dnatic09 right on time. The JRE 17 is up: https://hub.docker.com/r/azagniotov/stubby4j/tags 

Would you be able to sanity check the ARM 64 images?

**Comment by azagniotov** [comment]
In the meanwhile, I will close the issue. Feel free to reopen

**Comment by dnatic09** [comment]
@aservedio-swi, you can port the AV environments to use this.
