### ISSUE TITLE
[QUESTION] Is it possible to configure websocket server to return different results

### ISSUE THREAD

**Issue by toerni** [azagniotov/stubby4j#459]
Stubby websocket server can be configured to return a certain response on connection time.
With the delay, you can specifiy how much time passes between each send
However, I can't get stubby to send a different response every time the delay passes.
Eg., after a second send response 1, after two seconds, send response 2 en after 3 seconds a third response

**Comment by azagniotov** [comment]
Hey @toerni ,

Thank you for the question. 

Unfortunately, although this is supported in stubby4j on HTTP (I am quoting stubby's [HTTP docs](https://stubby4j.com/docs/http_endpoint_configuration_howto.html#response) `Response object properties` section):
```
When sequenced responses is configured, on each incoming request to the same URI,
a subsequent response in the list will be sent to the client. The sequenced responses
play in a cycle (loop). In other words: after the response sequence plays through,
the cycle restarts on the next incoming request.
```
I do not have an equivalent functionality for web sockets ... I can try to find a time next week to make a PR

**Comment by Kamali20-gan** [comment]
Hi, I need this feature for my automation as well .. Has this been implemented ?
Thanks

**Comment by Kamali20-gan** [comment]
I guess we can achieve this by configuring on-message for the client to send a particular message and upon receiving that message we can send the desired response .. But our automation is in python and am trying to figure out how to send a WebSocket message to admin portal from python code .. any help or tips to achieve this is really appreciated :)

**Comment by azagniotov** [comment]
Started work

**Comment by azagniotov** [comment]
Done. Please have a look: https://stubby4j.com/docs/websockets_configuration_howto.html#server-response-required 

I will try to release the `v7.6.1` in the next few days to Maven Central and DockerHub. In the meanwhile, this is available in the `latest` tag on DockerHub
