### ISSUE TITLE
not able to see request and response body after enableing --debul logs even

### ISSUE THREAD

**Issue by sanjay19834U** [azagniotov/stubby4j#46]
I used ConsoleUtils.enableDebug(true) to get request and response bodies on console, but not able to get .
 Kindly look into it, in our use case requirement in which when any request gets failed at stubby's end then we want to see request and response body for debugging , but currently it is not dumping the same

**Comment by azagniotov** [comment]
Please user `--debug` command line argument if you are running stubby using the `java -jar ...` command
