### ISSUE TITLE
"gradle install"  not working correctly

### ISSUE THREAD

**Issue by AntoineBro** [azagniotov/stubby4j#48]
running  **gradle install**  creates the following jars under  **~/.m2/repository/stubby4j/main/3.2.3-SNAPSHOT** :
```
├── main-3.2.3-SNAPSHOT-javadoc.jar
├── main-3.2.3-SNAPSHOT-no-dependencies.jar
├── main-3.2.3-SNAPSHOT-sources.jar
├── main-3.2.3-SNAPSHOT.jar
├── main-3.2.3-SNAPSHOT.pom
└── maven-metadata-local.xml
```

is there a task that allows deploying the correct jar in the local maven repository ?

**Comment by azagniotov** [comment]
Hi. Thank you for your question.

I have never tried to install the jars into a local repo, to be honest. 
Just running the `gradle` command will generate correct jars under `target/`libs`. I do not have a task to deploy the correct jar(s) to the local maven repository

**Comment by azagniotov** [comment]
Hi @AntoineBro , I know this is waaaaay too late, but just FYI:
https://github.com/azagniotov/stubby4j#installing-stubby4j-to-local-m2-repository
