### ISSUE TITLE
Quick start - setup not working

### ISSUE THREAD

**Issue by tracybporter** [azagniotov/stubby4j#52]
I followed the instructions for downloading the latest jar and created a yaml file exactly like the example. When I try a GET request (curl and chrome and postman) I get a 404 for the hello-world uri and 500 for status.

**Comment by azagniotov** [comment]
Hi, just to confirm - we are talking about version v3.3.0? 
Can you please provide the stubby startup command? Also, can you please provide the YAML you are using?

Thanks

**Comment by tracybporter** [comment]
I just tried the steps on a different computer and they work. At this time
I believe the issue is mine. I am now going to crack open the other
computer and see how I messed up.

Thank you for your quick response.

Sorry to have bothered you.

VERY cool tool. I've build 2 similar apps, but not with nearly the slick
options.

Sincerely,

Tracy.

**Comment by azagniotov** [comment]
No worries. Thank you. Lemme know if you experiencing any issues. 

P.S. These "different" computers - do they have a different OS?

**Comment by tracybporter** [comment]
Kinda. One is El Capitan and the other Yosemite.

**Comment by azagniotov** [comment]
Ok, at least both are OSX

On Thu, Feb 4, 2016 at 6:09 PM, Tracy B. Porter <notifications@github.com>
wrote:

> Kinda. One is El Capitan and the other Yosemite.
>
> Sent from my iPhone
>
> > On Feb 4, 2016, at 7:20 PM, Alexander Zagniotov <
> notifications@github.com> wrote:
> >
> > No worries. Thank you. Lemme know if you experiencing any issues.
> >
> > P.S. These "different" computers - do they have a different OS?
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azagniotov/stubby4j/issues/52#issuecomment-180157121>.
>



-- 
Sincerely,
Alexander Zagniotov

LinkedIn: http://linkedin.com/in/AlexanderZagniotov
Twitter: http://twitter.com/AlexZagniotov
Blog: https://medium.com/@AlexZagniotov
About.Me: http://about.me/AlexZagniotov

Sent from my Mac Computer Hardware Pro

**Comment by tracybporter** [comment]
The problem was user error....me! My yaml file was not correct. Thank you again for the speedy response.

**Comment by azagniotov** [comment]
No worries! I am glad you found the problem.

On Sun, Feb 7, 2016 at 11:13 AM, Tracy B. Porter <notifications@github.com>
wrote:

> The problem was user error....me! My yaml file was not correct. Thank you
> again for the speedy response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azagniotov/stubby4j/issues/52#issuecomment-181087765>.
>



-- 
Sincerely,
Alexander Zagniotov

LinkedIn: http://linkedin.com/in/AlexanderZagniotov
Twitter: http://twitter.com/AlexZagniotov
Blog: https://medium.com/@AlexZagniotov
About.Me: http://about.me/AlexZagniotov

Sent from my Mac Computer Hardware Pro
