### ISSUE TITLE
regex doesn't work for multiline request body

### ISSUE THREAD

**Issue by amitgupta-work** [azagniotov/stubby4j#53]
I am capturing request in stubby4j like this

```
-  request:
      method: POST
      url: /someUrl
      post: ".*(amit).*"
```
It works fine if I use single line in request body. E.g. `User name is amit gupta`. But it fails if I use multiline text as

```
User name is amit gupta 
secondline
```
How can I match some part of request body?

I need to do this. Because any extra space in post body leads 404. And even this approach doesn't work

```
      post: >
        .*(amit).*
```

**Comment by amitgupta-work** [comment]
Never mind. I got the answer on stackoverflow. I need to use \s and \s

**Comment by azagniotov** [comment]
Great!
