### ISSUE TITLE
Record&Replay: regex being send in place of the actual query or header value

### ISSUE THREAD

**Issue by rrabio** [azagniotov/stubby4j#61]
When a response is recorded with Record&Replay, the regex values in the header and query fields are used to create the request sent to the server specified in the response.body field. The actual value should be used instead. 
Example:
a request such as :
http://myserver/Search?queryvalue=ciao

intercepted by the following yaml request:
-  request:
      method: GET
      url: /search
      query:
         queryvalue: "([a-zA-Z]+)"
   response:
      status: 200
      body: http://127.0.0.1:8888

will create an http request for 127.0.0.1:8888 that will contain a queryvalye=([a-zA-Z]+) rather than a queryvalue=ciao.

**Comment by rrabio** [comment]
PS. great tool Alexander and thanks for sharing it!
I'm willing to fix the bug if you agree and propose a patch, if you can give me a few pointers on where and how. 
Cheers

**Comment by azagniotov** [comment]
Hi @rrabio , thanks for reporting this. I already have a fix. Will you be able to build a SNAPSHOT from the `master`, once I push the fix and test it on your end before I deploy it to Maven Central?

**Comment by azagniotov** [comment]
Fixed in version `4.0.4`

**Comment by azagniotov** [comment]
Btw, it is a little bit tricky with headers. Sending incoming request headers as-is can affect the recorded response. For now, sending only  incoming request query string as-is

**Comment by rrabio** [comment]
It works perfectly now, thanks!

**Comment by azagniotov** [comment]
Releasing version 4.0.4
