### ISSUE TITLE
Is there way to load multiple YAML files? 

### ISSUE THREAD

**Issue by pallapothurameshbabu** [azagniotov/stubby4j#67]
Is there way to load multiple YAML files? 

Below command is taking only ine file.
java -jar stubby4j-5.0.0.jar -d stubby4j_data.yaml

Thanks !!

**Comment by azagniotov** [comment]
Hello, you cannot load multiple YAML files with `-d`, but your main YAML can refer to other YAMLs

**Comment by pallapothurameshbabu** [comment]
could you please share example for same ?

Thanks !!

**Comment by azagniotov** [comment]
Read about the: https://github.com/azagniotov/stubby4j#file and https://github.com/azagniotov/stubby4j#file-1 and https://github.com/azagniotov/stubby4j#command-line-switches (`--watch`)

**Comment by pallapothurameshbabu** [comment]
Thank you !!!
