### ISSUE TITLE
Append new requests

### ISSUE THREAD

**Issue by leonardocaldas** [azagniotov/stubby4j#80]
I'm only able to replace all the loaded stubs using the available admin endpoint, so if I for instance load an YAML file and then, at runtime, want to add a new endpoint, I have to send all the stubs that were already there plus my new one, when I could just send only the new one.

Something like the below would be nice:
```
POST http://localhost:8889/append -d'
{
...stub configuration
}'
```

**Comment by azagniotov** [comment]
Yes, you cannot append if you POST programmatically. But, stubby supports hot reload of the YAML file. Which mean, if this is feasible, you could edit the file and it will get reloaded. 

Btw, pull requests are welcomed :)
