### ISSUE TITLE
Startup behavior differs from documentation

### ISSUE THREAD

**Issue by leonardocaldas** [azagniotov/stubby4j#81]
In the documentation we have the following section:
```
Supplying endpoints to stubby

Submit POST requests to localhost:8889 or load a data-file (using -d / --data flags) with the following structure for each endpoint:"
```
I tried to run the stubby.jar without setting the -d flag and got the following error:
```
YAML data was not provided using command line option '--data'
```
So, either the **or** in documentation is confuse, because makes me believe that the -d flag is optional, which apparently is not, or this really should be possible, but there is some kind of bug in latest release.

**Comment by azagniotov** [comment]
Yeah. The `or` in documentation is confusing. Will update. Thanks
