### ISSUE TITLE
Move to SLF4J instead of ANSITerminal

### ISSUE THREAD

**Issue by asarkar** [azagniotov/stubby4j#82]
The `ANSITerminal` is cute and all, but in an enterprise setting, it's not useful. For any non-trivial deployment, log management is serious business, and having a bunch of colorful console logs doesn't help with that. Not to mention some of the output is in black, and is not visible on a black console (who thought it was a good idea?).

I suggest that `ANSITerminal` be replaced with SLF4J. stubby4j doesn't need to, and shouldn't, package a particular runtime for SLF4J, and leave it to the user to choose their own logging implementation.

**Comment by azagniotov** [comment]
@asarkar all valid points.Would you be happy to issue a PR?

**Comment by asarkar** [comment]
A quick search shows 18 references to `ANSITerminal`; I may be able to put together a PR.

**Comment by asarkar** [comment]
I was wrong, there are many more references. I made the changes, however, there appears to be tests that validate console output and are failing. Such tests are fragile, and IMO, serve no purpose. If you insist on keeping them, I'm afraid I'll have to pass on the PR.
WDYT?

**Comment by azagniotov** [comment]
Well, @asarkar if `ANSITerminal` is going away, then the respective tests must go too because the behavior has changed. So, please go ahead and remove the tests. Thank you for your time

**Comment by asarkar** [comment]
https://github.com/azagniotov/stubby4j/pull/83

**Comment by asarkar** [comment]
Hello @azagniotov

**Comment by azagniotov** [comment]
Hello!

Vacations. I will address this soon! Thank you for following up!

**Comment by azagniotov** [comment]
@asarkar looking at this now

**Comment by azagniotov** [comment]
FYI, I released a new version `5.1.0` to Maven which includes the current change.
