### ISSUE TITLE
StubsResponseHandlingStrategyFactory doesn't honor 404 responses

### ISSUE THREAD

**Issue by MannanM** [azagniotov/stubby4j#92]
If you set a custom stub to return a 404 response with payload, 

```
   response:
      status: 404
      body: { "foo": "bar" }
```
Stubby4J doesn't honor it and instead uses the `NotFoundResponseHandlingStrategy`. 
```
    public static StubResponseHandlingStrategy getStrategy(final StubResponse foundStubResponse) {
        final HttpStatus.Code httpStatusCode = foundStubResponse.getHttpStatusCode();
        switch (httpStatusCode) {
            case NOT_FOUND:
                return new NotFoundResponseHandlingStrategy();
```
I think it should at least check if the `StubResponse` has a body, and if so use the `DefaultResponseHandlingStrategy` instead.

**Comment by azagniotov** [comment]
Thank you. I will try to address it soon

**Comment by azagniotov** [comment]
This functionality will be available in the next release tomorrow
